import { StyleSheet } from "react-native";

export const ACCENT_COLOR = "#3C6EC8";

export const styles = StyleSheet.create({
  // Main Container
  container: {
    flex: 1,
    backgroundColor: "#f5f5f5",
  },
  scrollContainer: {
    flex: 1,
    padding: 20,
  },
  header: {
    marginBottom: 20,
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "center",
    minHeight: 40,
  },
  backButton: {
    position: "absolute",
    left: 0,
    width: 40,
    height: 40,
    borderRadius: 20,
    alignItems: "center",
    justifyContent: "center",
    zIndex: 10,
  },
  backButtonText: {
    fontSize: 24,
    color: "#333",
    fontWeight: "bold",
    lineHeight: 28,
  },
  title: {
    fontSize: 24,
    fontWeight: "bold",
    color: "#333",
  },
  section: {
    marginBottom: 20,
    backgroundColor: "#fff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ddd",
  },
  sectionHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 12,
    backgroundColor: "#fcfcfc",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
    borderTopLeftRadius: 8,
    borderTopRightRadius: 8,
  },
  sectionContent: {
    padding: 12,
  },
  sectionTitle: {
    fontSize: 16,
    fontWeight: "bold",
    color: ACCENT_COLOR,
  },
  collapseIcon: {
    fontSize: 20,
    fontWeight: "bold",
    color: "#999",
    width: 20,
    textAlign: "center",
  },
  inputRow: {
    flexDirection: "row",
    alignItems: "center",
    justifyContent: "space-between",
    marginBottom: 12,
  },
  labelContainer: {
    flex: 1,
    flexDirection: "row",
    alignItems: "center",
    marginRight: 10,
  },
  labelText: {
    fontSize: 14,
    color: "#333",
  },
  controlWrapper: {
    width: 140,
  },
  input: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 6,
    padding: 10,
    fontSize: 14,
    backgroundColor: "#fafafa",
    width: "100%",
    color: "#333",
  },
  dropdownButton: {
    borderWidth: 1,
    borderColor: "#ccc",
    borderRadius: 6,
    padding: 10,
    backgroundColor: "#fafafa",
    width: "100%",
  },
  dropdownButtonText: {
    fontSize: 14,
    color: "#333",
  },
  dropdownList: {
    backgroundColor: "#fff",
    borderWidth: 1,
    borderColor: "#bbb",
    borderRadius: 6,
    marginTop: 4,
  },
  dropdownModalContainer: {
    ...StyleSheet.absoluteFillObject,
    zIndex: 2000,
  },
  dropdownBackdrop: {
    ...StyleSheet.absoluteFillObject,
  },
  dropdownModalList: {
    position: "absolute",
    zIndex: 2001,
  },
  dropdownItem: {
    padding: 12,
    borderBottomWidth: 1,
    borderBottomColor: "#f0f0f0",
  },
  dropdownItemText: {
    fontSize: 14,
    color: "#333",
  },
  controls: {
    flexDirection: "row",
    marginVertical: 20,
    justifyContent: "center",
  },
  button: {
    flex: 1,
    backgroundColor: ACCENT_COLOR,
    padding: 14,
    borderRadius: 8,
    alignItems: "center",
    justifyContent: "center",
    borderWidth: 1,
    borderColor: "rgba(0,0,0,0.1)",
  },
  buttonDisabled: {
    backgroundColor: "#ccc",
  },
  buttonText: {
    color: "#fff",
    fontWeight: "bold",
    fontSize: 16,
  },
  progressBarContainer: {
    height: 6,
    backgroundColor: "#eee",
    borderRadius: 3,
    marginTop: 15,
    overflow: "hidden",
  },
  progressBarFill: {
    height: "100%",
    backgroundColor: ACCENT_COLOR,
  },
  resultBox: {
    backgroundColor: "#f9f9f9",
    padding: 15,
    borderRadius: 8,
    marginBottom: 20,
    borderWidth: 1,
    borderColor: "#eee",
  },
  resultText: {
    fontSize: 13,
    color: "#444",
    fontFamily: "monospace",
    lineHeight: 18,
  },
  logBatchContainer: {
    backgroundColor: "#fff",
    borderRadius: 8,
    borderWidth: 1,
    borderColor: "#ddd",
    marginBottom: 15,
    overflow: "hidden",
  },
  logBatchHeader: {
    flexDirection: "row",
    justifyContent: "space-between",
    alignItems: "center",
    padding: 12,
    backgroundColor: "#f5f5f5",
    borderBottomWidth: 1,
    borderBottomColor: "#eee",
  },
  logBatchTitle: {
    fontSize: 14,
    fontWeight: "bold",
    color: "#333",
  },
  logBatchTime: {
    fontSize: 11,
    color: "#666",
    marginTop: 2,
  },
  copyButton: {
    backgroundColor: ACCENT_COLOR,
    paddingHorizontal: 12,
    paddingVertical: 6,
    borderRadius: 4,
  },
  copyButtonText: {
    fontSize: 12,
    color: "#fff",
    fontWeight: "600",
  },
  logEntries: {
    padding: 12,
    backgroundColor: "#fafafa",
    maxHeight: 300,
  },
  logText: {
    fontSize: 11,
    marginBottom: 2,
    color: "#333",
    fontFamily: "monospace",
  },
  logTimestamp: {
    color: "#888",
  },
  fieldContainer: {
    marginVertical: 20,
    backgroundColor: "#fff",
    borderRadius: 12,
    padding: 15,
    borderWidth: 1,
    borderColor: "#ddd",
  },
  field: {
    backgroundColor: "#f0f0f0",
    position: "relative",
    borderRadius: 8,
  },
  legend: {
    flexDirection: "row",
    justifyContent: "center",
    flexWrap: "wrap",
    marginTop: 10,
  },
  legendItem: {
    flexDirection: "row",
    alignItems: "center",
    marginRight: 15,
    marginBottom: 8,
  },
  legendText: {
    fontSize: 12,
    color: "#666",
  },
  legendMarkerBase: {
    width: 10,
    height: 10,
    borderRadius: 5,
    borderWidth: 1,
    borderColor: "#fff",
    marginRight: 6,
  },
  checkboxRow: {
    flexDirection: "row",
    alignItems: "center",
    marginBottom: 15,
    paddingVertical: 5,
  },
  checkbox: {
    width: 22,
    height: 22,
    borderWidth: 2,
    borderColor: ACCENT_COLOR,
    borderRadius: 4,
    marginRight: 12,
    backgroundColor: "#fff",
    alignItems: "center",
    justifyContent: "center",
  },

  checkboxChecked: {
    backgroundColor: ACCENT_COLOR,
  },
});
